version: "3"

services:

  # Database

  postgres:
    image: postgres:alpine
    container_name: postgres
    env_file:
      - .env

  # Backend

  web:
    build:
      context: ./server
    container_name: web
    depends_on:
      - postgres
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - .env
    environment:
      - BASE_URL="http://localhost:2000"
    working_dir: /app
    volumes:
      - ./server:/app

  # Frontend

  node:
    build:
      context: ./client
    working_dir: /app
    env_file:
      - .env
    ports:
      - "${PORT:-2000}:2000"
    volumes:
      - ./client:/app
