#!/bin/bash

set -e

host="postgres"

echo "Attempting to connect to PostgreSQL @ ${host}:5432"

while nc -z ${host} 5432; ret=$?; [[ ${ret} -ne 0 ]]; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done

>&2 echo "Postgres is up starting the seeding"

python /app/run/seed_db.py

exec $@
